{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "otel-services.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otel-services.labels" . | nindent 4 }}
  annotations:
  {{- if eq .Values.ingress.className "alb" }}
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80, "HTTPS": 443}]'
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/group.name: locals-alb
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{.Values.ingress.subDomainName }}.{{ .Values.ingress.domainName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-proxy
                port:
                  number: 8080
  tls:
    - hosts:
        - "*.{{ .Values.ingress.domainName }}"
      secretName: {{ include "otel-services.fullname" . }}-tls
{{- end }}

