{{- if .Values.services.productReviews.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.productReviews.name }}
  labels:
    opentelemetry.io/name: {{ .Values.services.productReviews.name }}
    app.kubernetes.io/component: {{ .Values.services.productReviews.name }}
    app.kubernetes.io/name: {{ .Values.services.productReviews.name }}
    app.kubernetes.io/version: "2.1.3"
    app.kubernetes.io/part-of: opentelemetry-demo
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.services.productReviews.port }}
      name: tcp-service
      targetPort: {{ .Values.services.productReviews.port }}
      protocol: TCP
  selector:
    opentelemetry.io/name: {{ .Values.services.productReviews.name }}
---
{{- end }}
{{- if .Values.services.llm.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.llm.name }}
  labels:
    opentelemetry.io/name: {{ .Values.services.llm.name }}
    app.kubernetes.io/component: {{ .Values.services.llm.name }}
    app.kubernetes.io/name: {{ .Values.services.llm.name }}
    app.kubernetes.io/version: "2.1.3"
    app.kubernetes.io/part-of: opentelemetry-demo
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.services.llm.port }}
      name: tcp-service
      targetPort: {{ .Values.services.llm.port }}
      protocol: TCP
  selector:
    opentelemetry.io/name: {{ .Values.services.llm.name }}
{{- end }}

