dist:
  name: otelcol-dev
  description: Basic OTel Collector distribution for Developers
  output_path: ./otelcol-dev
  cgo_enabled: true

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.139.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.139.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.139.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/opensearchexporter v0.139.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awss3exporter v0.139.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.139.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.139.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.139.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor v0.139.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.139.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.139.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.139.0
  - gomod: github.com/honeycombio/opentelemetry-collector-symbolicator/sourcemapprocessor v1.0.2
  - gomod: github.com/honeycombio/opentelemetry-collector-symbolicator/proguardprocessor v1.0.0
  - gomod: github.com/honeycombio/opentelemetry-collector-symbolicator/dsymprocessor v1.0.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.139.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver v0.139.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.139.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zipkinreceiver v0.139.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver v0.139.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.139.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/nginxreceiver v0.139.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/redisreceiver v0.139.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver v0.139.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/httpcheckreceiver v0.139.0

connectors:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/spanmetricsconnector v0.139.0

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.139.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.45.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.45.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.45.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.45.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.45.0

# replaces:
#  - github.com/honeycombio/opentelemetry-collector-symbolicator/proguardprocessor => github.com/martinjt/opentelemetry-collector-symbolicator/proguardprocessor v0.0.3-devrel
#  - github.com/honeycombio/opentelemetry-collector-symbolicator/sourcemapprocessor => github.com/martinjt/opentelemetry-collector-symbolicator/sourcemapprocessor v0.0.3-devrel
#  - github.com/honeycombio/opentelemetry-collector-symbolicator/dsymprocessor => github.com/martinjt/opentelemetry-collector-symbolicator/dsymprocessor v0.0.3-devrel
