dist:
  name: otelcol-dev
  description: Basic OTel Collector distribution for Developers
  output_path: ./otelcol-dev

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.135.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.135.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/opensearchexporter v0.135.0
  # Add to enable S3 export in my environment
  - gomod: github.com/honeycombio/enhance-indexing-s3-exporter/enhanceindexings3exporter v0.0.6

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor v0.135.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.135.0
  - gomod: github.com/honeycombio/opentelemetry-collector-symbolicator/sourcemapprocessor v0.0.10
  - gomod: github.com/honeycombio/opentelemetry-collector-symbolicator/dsymprocessor v0.0.6
  - gomod: github.com/honeycombio/opentelemetry-collector-symbolicator/proguardprocessor v0.0.4
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.135.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zipkinreceiver v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/nginxreceiver v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/redisreceiver v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/httpcheckreceiver v0.135.0

connectors:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/spanmetricsconnector v0.135.0

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.135.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.18.0

replaces:
  - github.com/honeycombio/opentelemetry-collector-symbolicator/proguardprocessor => github.com/martinjt/opentelemetry-collector-symbolicator/proguardprocessor v0.0.3-devrel
  - github.com/honeycombio/opentelemetry-collector-symbolicator/sourcemapprocessor => github.com/martinjt/opentelemetry-collector-symbolicator/sourcemapprocessor v0.0.3-devrel
  - github.com/honeycombio/opentelemetry-collector-symbolicator/dsymprocessor => github.com/martinjt/opentelemetry-collector-symbolicator/dsymprocessor v0.0.3-devrel
